--!
-- SQL table dump from CSV file: elements (elements.csv -> elements.sql)
-- Generated by: ccsv2sql 1.0 (https://github.com/stpettersens/ccsv2sql)
-- Generated at: 2015-04-18 22:58:42.548327

DROP TABLE IF EXISTS `elements`;
CREATE TABLE IF NOT EXISTS `elements` (
`_id` VARCHAR(30),
`element` VARCHAR(50),
`type` VARCHAR(50),
`symbol` VARCHAR(50),
`createdAt` TIMESTAMP)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `elements` VALUES (
'287be3c78d0645d1911dcf29',
'Oxygen',
'gas',
'O',
'2015-01-01 14:00:00');

INSERT INTO `elements` VALUES (
'55bfe60ef1924e22a4ec84a4',
'Hydrogen',
'gas',
'H',
'2015-01-01 15:10:12');
